### ISSUE TITLE
TypeError: _this7._config.server.rewriteRequestUrl is not a function React native 0.64.0

### ISSUE THREAD

**Issue by San10694** [react-native-community/upgrade-support#169]
## Things I’ve done to figure out my issue

- [ ] I used [upgrade-helper](https://react-native-community.github.io/upgrade-helper/) to do my upgrade.

**Comment by dishpanda** [comment]
Were you able to find a solution to this issue?

**Comment by San10694** [comment]
@dishpanda 
no still struggling 
can anyone please help here

**Comment by amleonardccsd** [comment]
What does your package.json look like? I I had a "resolution" field with metro-config 0.57.0 in it, and that was overriding the version of metro-config that metro needs.

**Comment by AdityaPahilwani** [comment]
@amleonardccsd how did you solved it? I tried to remove mero-confif from resolution  field still faces the same issue

**Comment by AdityaPahilwani** [comment]
I would suggest to bump up your metro version.

I faces a similar issue and the issue was with metro version conflicts.

Our metro version was 0.56 and when migrating from 0.63 to 0.64 and @react-native-community/cli metro version gets bumped to 0.64.0.

Because of this metro resolution was failing and throwed this error
