### ISSUE TITLE
TypeError: func.apply is not a function

### ISSUE THREAD

**Issue by Goldyukol** [react-native-community/upgrade-support#51]
The application before version 0.62, an error started popping up at me

![Screenshot_2020-04-14-20-43-35-909_com minskapple beremennostplusfree](https://user-images.githubusercontent.com/50366889/79051303-29d41880-7c38-11ea-9341-f76704accec0.jpg)

**Comment by lucasbento** [comment]
Wwe need a lot more information in order to help with this, please fill in another issue following the issue template specified at the beginning.

Also try to provide relevant code, whether or not it worked on `0.61.5` and if possible a project to reproduce the error you are experience.
