### ISSUE TITLE
Invariant Violation: "Appname" has not been registered

### ISSUE THREAD

**Issue by sandeeptheminery** [react-native-community/upgrade-support#224]
React Native ios app - XCode(Version 13.2.1) , Mac M1

## `react-native info` log
warn Package react-native-firebase contains invalid configuration: "dependency.platforms.ios.podspecPath" is not allowed. Please verify it's properly linked using "react-native config" command and contact the package maintainers about this.
warn Package rn-fetch-blob contains invalid configuration: "dependency.hooks" is not allowed. Please verify it's properly linked using "react-native config" command and contact the package maintainers about this.
info Fetching system and libraries information...
(node:10196) Warning: Accessing non-existent property 'padLevels' of module exports inside circular dependency
(Use `node --trace-warnings ...` to show where the warning was created)
System:
    OS: macOS 12.2.1
    CPU: (8) x64 Apple M1
    Memory: 35.66 MB / 8.00 GB
    Shell: 5.8 - /bin/zsh
  Binaries:
    Node: 16.10.0 - /usr/local/bin/node
    Yarn: 1.22.17 - /usr/local/bin/yarn
    npm: 8.19.3 - /opt/homebrew/bin/npm
    Watchman: 2022.03.21.00 - /opt/homebrew/bin/watchman
  Managers:
    CocoaPods: 1.11.3 - /opt/homebrew/bin/pod
  SDKs:
    iOS SDK:
      Platforms: DriverKit 21.2, iOS 15.2, macOS 12.1, tvOS 15.2, watchOS 8.3
    Android SDK: Not Found
  IDEs:
    Android Studio: Not Found
    Xcode: 13.2.1/13C100 - /usr/bin/xcodebuild
  Languages:
    Java: Not Found
  npmPackages:
    @react-native-community/cli: ^10.1.3 => 10.1.3 
    react: 18.2.0 => 18.2.0 
    react-native: 0.71.1 => 0.71.1 
    react-native-macos: Not Found
  npmGlobalPackages:
    *react-native*: Not Found

## Things I’ve done to figure out my issue

- [ yes] I used [upgrade-helper](https://react-native-community.github.io/upgrade-helper/?from=0.61.5&to=0.71.1) to do my upgrade.

upgraded from react native 0.61.5 to 0.71.1

## Description

After upgrading the ios app build works but while loading on simulator it throws this error

Invariant Violation: "Appname" has not been registered. This can happen if:
* Metro (the local dev server) is run from the wrong folder. Check if Metro is running, stop it and restart it in the current project.
* A module failed to load due to an error and `AppRegistry.registerComponent` wasn't called., js engine: hermes

I checked appName in AppRegistry.registerComponent its correct and same as before upgrade.
I also tried reset cache,  removed simulator data and also rebuild the project again but it didn't work, please help!

![image](https://user-images.githubusercontent.com/70523645/214947160-5adaced9-f9e8-40fc-9541-8bcb22ee5200.png)

**Comment by fgarcia92** [comment]
I'm facing the same issue upgrading to 0.71.1 with M1

**Comment by jarapamikaella** [comment]
hi guys! did you have any updates with this? facing this issue also with 0.71.1, upgraded to 0.71.1 in react native because of app crash issue due to modals

**Comment by feige-2011** [comment]
> I'm facing the same issue upgrading to 0.71.1 with M1

I don't know if you have solved this problem. I hope you can be prompted. Thank you

**Comment by Ascor52** [comment]
I had the same error after upgrading from 0.68.2 to 0.71.3
The Appname is case sensitive, so check all Appname strings in the code.

In my case it was the new line (9) in AppDelegate.mm
self.moduleName = @"Appname";  ==>  self.moduleName = @"appname";

**Comment by theambidextrous** [comment]
Am stuck with this issue... anyone with a solution?

**Comment by renopp** [comment]
I have the same error on the Android platform

The way I fix this:
1. Disable the Hermes engine and use the JSC engine
2. After using the JSC engine the error will be seen coming from

**Comment by renopp** [comment]
try to upgrade react-native-reanimated

`"react-native-reanimated": "3.0.2"`

I fix this error at android platform

**Comment by renopp** [comment]
> Am stuck with this issue... anyone with a solution?

Have you tried to use the JSC engine?
I solve the issue by disabling hermes engine and using JSC, after switching to JSC engine the error showed and it was caused by react-native-reanimated

**Comment by renopp** [comment]
> Am stuck with this issue... anyone with a solution?

@theambidextrous Have you tried to use the JSC engine?
I solve the issue by disabling hermes engine and using JSC, after switching to JSC engine the error showed and it was caused by react-native-reanimated

**Comment by ARIPRASATH4664** [comment]
> Appname is case sensitive, so c

This Worked 💯

**Comment by Pratik-2102** [comment]
I dont have AppDelegate.mm file in folder structure

**Comment by ARIPRASATH4664** [comment]
> I dont have AppDelegate.mm file in folder structure

@Pratik-2102 Do you have AppDelegate.m in the folder ?

**Comment by Pratik-2102** [comment]
yes. I have this file

> > I dont have AppDelegate.mm file in folder structure
> 
> @Pratik-2102 Do you have AppDelegate.m in the folder ?

**Comment by ARIPRASATH4664** [comment]
@Pratik-2102 Perfect please do change the name as per your Module name in AppDelegate.m 👍🏼  Hope that Works

**Comment by GusCarreno** [comment]
Also you can try signing & Capabilities and adding a team

**Comment by prox2** [comment]
for me the issue happen after upgrading from 0.63 to 0.68, fixed by updating this line in AppDelegate.mm 

` UIView *rootView = RCTAppSetupDefaultRootView(bridge, @"appName", nil);`

@"appName" => must match the name in package.json

**Comment by onurravli** [comment]
Also, you should check the name prop in `app.json` file.

**Comment by grishkovelli** [comment]
After I updated all packages with `yarn-upgrade-all` I got two errors:
1. `middleware is not a function (it is undefined), js engine: hermes` is related to redux
2.  `Invariant Violation: "MyAppName" has not been registered`

In my case importing of `thunk` was changed, so to solve the problem I replaced 

```js
import thunk from 'redux-thunk' // 2.4.2
```

with

```js
import { thunk } from 'redux-thunk' // 3.1.0
```

and no more errors.

**Comment by nalendro16** [comment]
While changing my `app.json` due changing .env file to staging. i though it will be ok if i didn't match this name to each other.

so keep in mind to always match this two name

```
{
  "displayName": "CatchyName",
  "name": "CatchyName"
}
```

**Comment by Arif-Malik-N** [comment]
In my case, I renamed the app using react-native-rename. After updating self.moduleName to the new name in AppDelegate.swift, it worked.

  override func application(_ application: UIApplication, didFinishLaunchingWithOptions launchOptions: [UIApplication.LaunchOptionsKey : Any]? = nil) -> Bool {

//updated new name here
    self.moduleName = "old" 
    self.dependencyProvider = RCTAppDependencyProvider()
    FirebaseApp.configure()
    // You can add your custom initial props in the dictionary below.
    // They will be passed down to the ViewController used by React Native.
    self.initialProps = [:]

    return super.application(application, didFinishLaunchingWithOptions: launchOptions)
  }
