### ISSUE TITLE
[Android] Upgrade from 0.66 to 0.67: error: package com.swmansion.reanimated does not exist import com.swmansion.reanimated.ReanimatedPackage

### ISSUE THREAD

**Issue by Pandazaur** [react-native-community/upgrade-support#198]
## Environment
```
System:
    OS: macOS 11.6.1
    CPU: (12) x64 Intel(R) Core(TM) i7-9750H CPU @ 2.60GHz
    Memory: 1011.40 MB / 16.00 GB
    Shell: 5.8 - /bin/zsh
  Binaries:
    Node: 16.15.0 - ~/.nvm/versions/node/v16.15.0/bin/node
    Yarn: Not Found
    npm: 8.5.5 - ~/.nvm/versions/node/v16.15.0/bin/npm
    Watchman: Not Found
  Managers:
    CocoaPods: 1.11.2 - /Users/alexandreborel/.rvm/gems/ruby-2.7.1/bin/pod
  SDKs:
    iOS SDK:
      Platforms: DriverKit 21.2, iOS 15.2, macOS 12.1, tvOS 15.2, watchOS 8.3
    Android SDK: Not Found
  IDEs:
    Android Studio: 2020.3 AI-203.7717.56.2031.7678000
    Xcode: 13.2/13C90 - /usr/bin/xcodebuild
  Languages:
    Java: 11.0.15 - /usr/bin/javac
  npmPackages:
    @react-native-community/cli: Not Found
    react: 17.0.2 => 17.0.2
    react-native: ^0.67.2 => 0.67.2
    react-native-macos: Not Found
  npmGlobalPackages:
    *react-native*: Not Found
```
## Things I’ve done to figure out my issue

- [x] I used [upgrade-helper](https://react-native-community.github.io/upgrade-helper/) to do my upgrade.

## Upgrading version

Upgrading to 0.67.2

## Description

When I'm running my app on Android after upgrading to 0.67.2, I have somes issues:
```
/Users/x/FrenchFounders/app-v4/android/app/build/generated/rncli/src/main/java/com/facebook/react/PackageList.java:97: error: package com.reactnativerate does not exist
import com.reactnativerate.RNRatePackage;
                          ^
/Users/x/FrenchFounders/app-v4/android/app/build/generated/rncli/src/main/java/com/facebook/react/PackageList.java:99: error: package com.swmansion.reanimated does not exist
import com.swmansion.reanimated.ReanimatedPackage;
                               ^
/Users/x/FrenchFounders/app-v4/android/app/build/generated/rncli/src/main/java/com/facebook/react/PackageList.java:210: error: cannot find symbol
      new RNRatePackage(),
          ^
  symbol:   class RNRatePackage
  location: class PackageList
/Users/x/FrenchFounders/app-v4/android/app/build/generated/rncli/src/main/java/com/facebook/react/PackageList.java:211: error: cannot find symbol
      new ReanimatedPackage(),
```

I tried to remove and rerun "npm install" but not working

**Comment by LucasHimelfarb** [comment]
You need to upgrade `react-native-reanimated` because your `react-native-reanimated` does not have the corresponding version `.aar` (node_modules/react-native-reanimated/android) of react-native.
